### ISSUE TITLE
npm install fails using node 12.5

### ISSUE THREAD

**Issue by andynog** [tendermint/js-abci#39]
When I clone the repository and try to run `npm install` using node version 12.5 I get the following error:
```
> tendermint-node@4.0.0 preinstall /home/andy/Development/js-abci/node_modules/tendermint-node
> rm -f ./bin/tendermint && touch ./bin/tendermint


> tendermint-node@4.0.0 install /home/andy/Development/js-abci/node_modules/tendermint-node
> node ./bin/download.js

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/home/andy/Development/js-abci/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/andy/Development/js-abci/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/andy/Development/js-abci/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

Doing some research found the link below suggesting to downgrade Node version. Downgrading node to version 11.15.0 it works

https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node

**Comment by KrishnaPG** [comment]
This https://github.com/nomic-io/tendermint-node/pull/8 is the fix I created for this issue for a similar package. Should work for this too. `unzip` was the culprit there.
